# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nic McPhee's UMM homepage
email: mcphee@morris.umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Materials for and from my courses, research, and other
  activities (Twitter, Flickr, etc.).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://facultypages.morris.umn.edu/~mcphee/" # the base hostname & protocol for your site
twitter_username: NicMcPhee
github_username:  NicMcPhee
gchat: mcphee@morris.umn.edu
office: Sci 1315 (downstairs at the east end of the Science office wing)
office_phone: 320-589-6320
science_division_phone: 320-589-6300
mailing_address: |
  Nic McPhee
  Division of Science and Mathematics
  University of Minnesota, Morris
  600 E. 4th Street
  Morris, MN 56267-2132
calendar_url: http://www.google.com/calendar/hosted/morris.umn.edu/embed?src=mcphee%40morris.umn.edu&ctz=America/Chicago&mode=WEEK

collections:
  courses:
    output: true
    permalink: /courses/:path/
    defaults:
      - values:
          layout: syllabus

# Build settings
markdown: kramdown
