# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nic McPhee's UMM homepage
email: mcphee@morris.umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Materials for and from my courses, research, and other
  activities (Twitter, Flickr, etc.).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://facultypages.morris.umn.edu/~mcphee/" # the base hostname & protocol for your site
twitter_username: NicMcPhee
github_username:  NicMcPhee

collections:
  courses:
    output: true
    permalink: /courses/:path/

# Build settings
markdown: kramdown
